### ISSUE TITLE
bower asset jQuery-QueryBuilder case mismatch

### ISSUE THREAD

**Issue by mermerkaya** [leandrogehlen/yii2-querybuilder#17]
jQuery-QueryBuilder should be small letter to load bower-assets. it wont work in linux env. bower asset creates directory in small letter

it should be public $sourcePath = '@bower/jquery-querybuilder/dist'; 

https://github.com/leandrogehlen/yii2-querybuilder/blob/666d0f37372e0e605c4edddb299aeb8d55ebd359/QueryBuilderAsset.php#L14

**Comment by zuicis** [comment]
> jQuery-QueryBuilder should be small letter to load bower-assets. it wont work in linux env. bower asset creates directory in small letter
> 
> it should be public $sourcePath = '@bower/jquery-querybuilder/dist';
> 
> https://github.com/leandrogehlen/yii2-querybuilder/blob/666d0f37372e0e605c4edddb299aeb8d55ebd359/QueryBuilderAsset.php#L14

Rly?  on debian 8-10 + yii latest version: 
```
bot@sandbox:/var/www/test/vendor/bower# ls -lah
drwxr-xr-x  4 www-data www-data 4.0K Sep  9 09:57 jQuery-QueryBuilder
drwxr-xr-x  5 www-data www-data 4.0K Aug 16  2018 jquery-treegrid
```

```
The file or directory to be published does not exist: /var/www/test/vendor/bower/jquery-querybuilder/dist
```

**Comment by leandrogehlen** [comment]
You can customize the property to solve problem

```php
  Yii::$container->set('leandrogehlen\querybuilder\QueryBuilderAsset',[
      'sourcePath' = '@bower/jQuery-QueryBuilder/dist'
  ]);
```
