### ISSUE TITLE
composer error

### ISSUE THREAD

**Issue by TonisOrmisson** [leandrogehlen/yii2-querybuilder#5]
Hi

i am getting an error while doing composer update
The "https://bower.herokuapp.com/packages/search/jquery-querybuilder" file could not be downloaded (HTTP/1.1 404 Not Found)

If i remove yii2-querybuilder from composer.json - all the rest of dependencies work fine. 
yii2-querybuilder is added in composer.json as "leandrogehlen/yii2-querybuilder": "*"

tried on also on a second (live) machine that should work fine otherwise and got the same result. 

any ideas?

**Comment by leandrogehlen** [comment]
is it possible to show your composer.json?

**Comment by TonisOrmisson** [comment]
json below. If I remove yii2-querybuilder all seems to be working fine

{
    "name": "Myproject",
    "description": "Mydescription",
    "keywords": ["key","words"],
    "homepage": "http://mypage.com/",
    "type": "project",
    "license": "",
    "support": {
        "issues": "http://issues.com"
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": ">=2.0.6",
        "yiisoft/yii2-bootstrap": "_",
        "yiisoft/yii2-swiftmailer": "_",
        "yiisoft/yii2-codeception": "^2.0",
        "yiisoft/yii2-authclient": "_",
        "dektrium/yii2-user":"0.9._@dev",
        "miloschuman/yii2-highcharts-widget": "_",
        "dektrium/yii2-rbac": "dev-master",
        "wbraganca/yii2-fancytree-widget": "dev-master",
        "2amigos/yii2-switch-widget": "~1.0",
        "kartik-v/yii2-export": "_",
        "kartik-v/yii2-grid": "@dev", 
        "kartik-v/yii2-mpdf": "@dev",
        "kartik-v/yii2-widgets": "_",
        "kartik-v/yii2-icons": "@dev",
        "kartik-v/yii2-tabs-x": "_",
        "filsh/yii2-flags": "_@dev",
        "composer-plugin-api": "^1.0",
        "2amigos/yii2-tinymce-widget" : "~1.1",
        "moonlandsoft/yii2-phpexcel": "_",
        "leandrogehlen/yii2-querybuilder": "_"
    },
    "require-dev": {
        "yiisoft/yii2-debug": "_",
        "yiisoft/yii2-gii": "_",
        "yiisoft/yii2-faker": "_"
    },
    "config": {
        "process-timeout": 1800
    },
    "scripts": {
        "post-create-project-cmd": [
            "yii\composer\Installer::postCreateProject"
        ]
    },
    "extra": {
        "yii\composer\Installer::postCreateProject": {
            "setPermission": [
                {
                    "runtime": "0777",
                    "web/assets": "0777",
                    "web/batik-1.7/temp": "0777",
                    "yii": "0755"
                }
            ],
            "generateCookieValidationKey": [
                "config/web.php"
            ]
        },
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    }
}

**Comment by TonisOrmisson** [comment]
Update ...
just ran it again and it worked flawlessly
Thanks anyway.
