### ISSUE TITLE
save definition of created query

### ISSUE THREAD

**Issue by philippfrenzel** [leandrogehlen/yii2-querybuilder#8]
Hi,

any plans to allow a "save" of the query beeing created by the user?

Thanks - Philipp

**Comment by leandrogehlen** [comment]
Hello @philippfrenzel, i think that feature already exists in jquery plugin

Is it something like this?
http://querybuilder.js.org/demo.html#import_export.

**Comment by philippfrenzel** [comment]
Hi,

kind of -> means the jQuery Plugin is returning the query structure - what I meant would be a JSON to QueryBuilder translator within your module ;)

Thanks for taking care!

Philipp

**Comment by philippfrenzel** [comment]
sorry, stupid me -> I just saw you can parse it already -- so thinking about "just storing" the json object to the database ;)

**Comment by leandrogehlen** [comment]
Exacly!! 👍
